name: Mirroring

on:
  push:
    branches: [ master ]

jobs:
  to_covid_hcs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.COVID_HCS_KOTLIN_TRANSKEY_TOKEN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - run: |
        git clone --bare 'https://${{ github.repository_owner}}:${{ github.token }}@github.com/${{ github.repository }}' repo
        cd repo
    - run: |
        git push --mirror "${{ secrets.COVID_HCS_KOTLIN_URL }}"
